[package]
name = "kdbg"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
colored.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json.workspace = true
anyhow.workspace = true
chrono.workspace = true
